const SOCKET_EVENTS = {
  MOVE_LOCATION: "MOVE_LOCATION",
  CHANGE_LOCATION: "CHANGE_LOCATION",
  APPEND_LOCATION: "APPEND_LOCATION",
  DELETE_LOCATION: "DELETE_LOCATION",
  INIT: "INIT",
  ROOM_INIT: "ROOM_INIT",
};

module.exports = {
  SOCKET_EVENTS,
};
