const SOCKET_EVENTS = {
  CHANGE_LOCATION: 'CHANGE_LOCATION',
  APPEND_LOCATION: 'APPEND_LOCATION',
  REMOVE_LOCATION: 'REMOVE_LOCATION',
  INIT: 'INIT',
  ROOM_INIT: 'ROOM_INIT',
};

module.exports = {
  SOCKET_EVENTS,
}
